service: Greeter
frameworkVersion: '2'

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  
package:
  individually: true

functions:
  greeter:
    handler: WithMiddyNet::WithMiddyNet.Greeter::Handler
    package:
      artifact: bin/Release/netcoreapp3.1/withMiddyNet.zip
    events:
      - httpApi:
          path: /greeting/{name}
          method: GET              
    iamRoleStatements:
      - Effect: "Allow"
        Action: ssm:GetParameter
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:*